package:
  name: smesh4pyocct
  version: "9.8.0.1"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxi-devel') }}       # [linux]
    - cmake
    - ninja

  host:
    - occt ==7.5.3
    - boost-cpp
    - tbb-devel
    - vtk
    - zlib
    - pthreads-win32  # [win]

  run:
    - occt ==7.5.3
    - vtk
    - boost-cpp
    - zlib
    - pthreads-win32 # [win]

test:
  source_files:
    - test
  requires:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}   # [linux]
    - {{ cdt('libxi-devel') }}        # [linux]
    - {{ cdt('mesa-libegl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}   # [linux]
    - {{ cdt('libselinux') }}         # [linux]
    - {{ cdt('libxdamage') }}         # [linux]
    - {{ cdt('libxfixes') }}          # [linux]
    - {{ cdt('libxxf86vm') }}         # [linux]
    - cmake
    - ninja
    - catch2

about:
  home: https://github.com/trelau/SMESH
  license: LGPL2.1
  license_family: LGPL
  summary: Mesh library from SALOME
  description: Standalone version of the meshing library from the Salome Platform.
